# Generated by Django 3.2.23 on 2023-12-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birthdy',
        ),
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.DateField(db_column='Birthday', default='2001-01-21'),
        ),
    ]
